package cass;

public class Inserts {
	public static final String INSERT_1_DEMO = "INSERT into t1.demo ("
			+	"num , "
			+	"datetimeorigination, "
			+	"callingpartynumber, "
			+	"callingpartyunicodeloginuserid, "
			+	"currentroutingreason, "
			+	"huntpilotdn, "
			+	"huntpilotpartition, "
			+	"lastredirectingroutingreason, "
			+	"origcause_location, "
			+	"origcause_value, "
			+	"origipaddr, "
			+	"origmediacap_maxframesperpacket, "
			+	"origmediacap_payloadcapability, "
			+	"origmediatransportaddress_ip, "
			+	"origmediatransportaddress_port, "
			+	"orignodeid, "
			+	"origprecedencelevel, "
			+	"origroutingreason, "
			+	"origspan, "
			+	"origvideocap_bandwidth, "
			+	"origvideocap_codec, "
			+	"origvideocap_resolution, "
			+	"origvideotransportaddress_ip)"
			+ 	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?) ";
	
	public static final String INSERT_1_PROJ = "INSERT into t1.project ("
			+	"num , "
			+	"datetimeorigination, "
			+	"callingpartynumber, "
			+	"callingpartyunicodeloginuserid, "
			+	"currentroutingreason, "
			+	"huntpilotdn, "
			+	"huntpilotpartition, "
			+	"lastredirectingroutingreason, "
			+	"origcause_location, "
			+	"origcause_value, "
			+	"origipaddr, "
			+	"origmediacap_maxframesperpacket, "
			+	"origmediacap_payloadcapability, "
			+	"origmediatransportaddress_ip, "
			+	"origmediatransportaddress_port, "
			+	"orignodeid, "
			+	"origprecedencelevel, "
			+	"origroutingreason, "
			+	"origspan, "
			+	"origvideocap_bandwidth, "
			+	"origvideocap_codec, "
			+	"origvideocap_resolution, "
			+	"origvideotransportaddress_ip)"
			+ 	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?) ";
	
	public static final String INSERT_2_DEMO = "INSERT into t2.demo ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";
	
	public static final String INSERT_2_PROJ = "INSERT into t2.project ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";

	public static final String INSERT_3_DEMO = "INSERT into t3.demo ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?) ";
	public static final String INSERT_3_PROJ = "INSERT into t3.project ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?) ";	    
		   
	
}
