package cass;

/**
 * contains INSERT statements for the SSTwriter. These are similar to prepared statements.
 * Obvious refactoring can be performed.
 * @author slmyers
 *
 */

public class Inserts {
	public static final String INSERT_1_MOD_DEMO = 
			"INSERT into modified_demo.t1 (num , datetimeorigination, "
			+		"callingpartynumber, callingpartyunicodeloginuserid, currentroutingreason, huntpilotdn, huntpilotpartition," 
			+		"lastredirectingroutingreason, origcause_location, origcause_value, origipaddr, origmediacap_maxframesperpacket, "
			+		"origmediacap_payloadcapability, origmediatransportaddress_ip, origmediatransportaddress_port, orignodeid,"
			+		 "origprecedencelevel, origroutingreason, origspan, origvideocap_bandwidth, origvideocap_codec,"
			+		 "origvideocap_resolution, origvideotransportaddress_ip)"
			+		 "VALUES" 
			+		"(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String INSERT_1_MOD_PROJ = "INSERT into modified_project.t1 ("
			+	"num , "
			+	"datetimeorigination, "
			+	"callingpartynumber, "
			+	"callingpartyunicodeloginuserid, "
			+	"currentroutingreason, "
			+	"huntpilotdn, "
			+	"huntpilotpartition, "
			+	"lastredirectingroutingreason, "
			+	"origcause_location, "
			+	"origcause_value, "
			+	"origipaddr, "
			+	"origmediacap_maxframesperpacket, "
			+	"origmediacap_payloadcapability, "
			+	"origmediatransportaddress_ip, "
			+	"origmediatransportaddress_port, "
			+	"orignodeid, "
			+	"origprecedencelevel, "
			+	"origroutingreason, "
			+	"origspan, "
			+	"origvideocap_bandwidth, "
			+	"origvideocap_codec, "
			+	"origvideocap_resolution, "
			+	"origvideotransportaddress_ip)"
			+ 	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?) ";
	
	public static final String INSERT_2_MOD_DEMO = "INSERT into modified_demo.t2 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";
	
	public static final String INSERT_2_MOD_PROJ = "INSERT into modified_project.t2 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";

	public static final String INSERT_3_MOD_DEMO = "INSERT into modified_demo.t3 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?) ";
	public static final String INSERT_3_MOD_PROJ = "INSERT into modified_project.t3 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?) ";    
	
	public static final String INSERT_4_MOD_DEMO = "INSERT INTO modified_demo.t4 ("
			+	"duration, "
			+	"count) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_4_MOD_PROJ = "INSERT INTO modified_project.t4 ("
			+	"duration, "
			+	"count) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_5_MOD_DEMO = "INSERT INTO modified_demo.t5 ("
			+	"callingnumber, "
			+	"callcount) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_5_MOD_PROJ = "INSERT INTO modified_project.t5 ("
			+	"callingnumber, "
			+	"callcount) "
			+	" VALUES ("
			+	"?, ?) ";
	public static final String INSERT_1_DEMO = 
			"INSERT into demo.t1 (num , datetimeorigination, "
			+		"callingpartynumber, callingpartyunicodeloginuserid, currentroutingreason, huntpilotdn, huntpilotpartition," 
			+		"lastredirectingroutingreason, origcause_location, origcause_value, origipaddr, origmediacap_maxframesperpacket, "
			+		"origmediacap_payloadcapability, origmediatransportaddress_ip, origmediatransportaddress_port, orignodeid,"
			+		 "origprecedencelevel, origroutingreason, origspan, origvideocap_bandwidth, origvideocap_codec,"
			+		 "origvideocap_resolution, origvideotransportaddress_ip)"
			+		 "VALUES" 
			+		"(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
	
	public static final String INSERT_1_PROJ = "INSERT into project.t1 ("
			+	"num , "
			+	"datetimeorigination, "
			+	"callingpartynumber, "
			+	"callingpartyunicodeloginuserid, "
			+	"currentroutingreason, "
			+	"huntpilotdn, "
			+	"huntpilotpartition, "
			+	"lastredirectingroutingreason, "
			+	"origcause_location, "
			+	"origcause_value, "
			+	"origipaddr, "
			+	"origmediacap_maxframesperpacket, "
			+	"origmediacap_payloadcapability, "
			+	"origmediatransportaddress_ip, "
			+	"origmediatransportaddress_port, "
			+	"orignodeid, "
			+	"origprecedencelevel, "
			+	"origroutingreason, "
			+	"origspan, "
			+	"origvideocap_bandwidth, "
			+	"origvideocap_codec, "
			+	"origvideocap_resolution, "
			+	"origvideotransportaddress_ip)"
			+ 	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?) ";
	
	public static final String INSERT_2_DEMO = "INSERT into demo.t2 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";
	
	public static final String INSERT_2_PROJ = "INSERT into project.t2 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"cdrrecordtype, "
			+	"destcause_location, "
			+	"destcause_value, "
			+	"destipaddr, "
			+	"destlegcallidentifier, "
			+	"destmediacap_maxframesperpacket, "
			+	"destmediacap_payloadcapability, "
			+	"destmediatransportaddress_ip, "
			+	"destmediatransportaddress_port, "
			+	"destnodeid, "
			+	"destprecedencelevel, "
			+	"destspan, "
			+	"finalcalledpartynumber, "
			+	"finalcalledpartyunicodeloginuserid, "
			+	"globalcallid_callid, "
			+	"globalcallid_callmanagerid, "
			+	"incomingprotocolcallref, "
			+	"incomingprotocolid, "
			+	"originalcalledpartynumber, "
			+	"origlegcallidentifier, "
			+	"origrsvpaudiostat, "
			+	"origrsvpvideostat, "
			+	"origvideotransportaddress_port, "
			+	"outgoingprotocolcallref, "
			+	"outgoingprotocolid)"
			+	" VALUES ("
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?, ?, ?, ?, "
			+ 	"?, ?) ";

	public static final String INSERT_3_DEMO = "INSERT into demo.t3 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?) ";
	public static final String INSERT_3_PROJ = "INSERT into project.t3 ("
			+	"num, "
			+	"datetimeorigination, "
			+	"datetimeconnect, "
			+	"datetimedisconnect, "
			+	"destcallterminationonbehalfof, "
			+	"destdevicename, "
			+	"destrsvpaudiostat, "
			+	"destrsvpvideostat, "
			+	"destvideocap_bandwidth, "
		    +	"destvideocap_bandwidth_channel2, "
		    +	"destvideocap_codec, "
		    +	"destvideocap_codec_channel2, "
		    +	"destvideocap_resolution, "
		    +	"destvideocap_resolution_channel2, "
		    +	"destvideochannel_role_channel2, "
		    +	"destvideotransportaddress_ip, "
		    +	"destvideotransportaddress_ip_channel2, "
		    +	"destvideotransportaddress_port, "
		    +	"destvideotransportaddress_port_channel2, "
		    +	"duration, "
		    +	"finalcalledpartynumberpartition, "
		    + 	"lastredirectdn, "
		    + 	"lastredirectdnpartition, "
		    +	"numberpartition, "
		    +	"origcalledpartyredirectonbehalfof, "
		    +	"origcallterminationonbehalfof, "
		    +	"origdevicename, "
		    +	"originalcalledpartynumberpartition, "
		    +	"pkid)"
		    +	" VALUES ("
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?, ?, "
		    + 	"?, ?, ?, ?) ";    
	
	public static final String INSERT_4_DEMO = "INSERT INTO demo.t4 ("
			+	"duration, "
			+	"count) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_4_PROJ = "INSERT INTO project.t4 ("
			+	"duration, "
			+	"count) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_5_DEMO = "INSERT INTO demo.t5 ("
			+	"callingnumber, "
			+	"callcount) "
			+	" VALUES ("
			+	"?, ?) ";
	
	public static final String INSERT_5_PROJ = "INSERT INTO project.t5 ("
			+	"callingnumber, "
			+	"callcount) "
			+	" VALUES ("
			+	"?, ?) ";
}
