package cass;

public class Schemas {

	public static final String SCHEMA_1_DEMO = "CREATE TABLE demo.t1  ( "
			+ "num bigint, "
			+ "datetimeorigination int, "
			+ "callingpartynumber int, "
			+ "callingpartyunicodeloginuserid text, "
			+ "currentroutingreason int, "
			+ "huntpilotdn text, "
			+ "huntpilotpartition text, "
			+ "lastredirectingroutingreason int, "
			+ "origcause_location decimal, "
			+ "origcause_value decimal, "
			+ "origipaddr text, "
			+ "origmediacap_maxframesperpacket int, "
			+ "origmediacap_payloadcapability int, "
			+ "origmediatransportaddress_ip text, "
			+ "origmediatransportaddress_port int, "
			+ "orignodeid int, "
			+ "origprecedencelevel decimal,"
			+ "origroutingreason int, "
			+ "origspan int, "
			+ "origvideocap_bandwidth int, "
			+ "origvideocap_codec float, "
			+ "origvideocap_resolution float, "
			+ "origvideotransportaddress_ip int, "
			+ "PRIMARY KEY ((num, datetimeorigination, origipaddr, origspan, currentroutingreason), orignodeid))";

	public static final String SCHEMA_1_PROJ = "CREATE TABLE project.t1  ( "
			+ "num bigint, "
			+ "datetimeorigination int, "
			+ "callingpartynumber int, "
			+ "callingpartyunicodeloginuserid text, "
			+ "currentroutingreason int, "
			+ "huntpilotdn text, "
			+ "huntpilotpartition text, "
			+ "lastredirectingroutingreason int, "
			+ "origcause_location decimal, "
			+ "origcause_value decimal, "
			+ "origipaddr text, "
			+ "origmediacap_maxframesperpacket int, "
			+ "origmediacap_payloadcapability int, "
			+ "origmediatransportaddress_ip text, "
			+ "origmediatransportaddress_port int, "
			+ "orignodeid int, "
			+ "origprecedencelevel decimal,"
			+ "origroutingreason int, "
			+ "origspan int, "
			+ "origvideocap_bandwidth int, "
			+ "origvideocap_codec float, "
			+ "origvideocap_resolution float, "
			+ "origvideotransportaddress_ip int, "
			+ "PRIMARY KEY ((num, datetimeorigination, origipaddr, origspan, currentroutingreason), orignodeid))";
	
	public static final String SCHEMA_2_DEMO = "CREATE TABLE demo.t2 ("
			+	"num bigint, "
			+	"datetimeorigination int, "
			+	"cdrrecordtype float, "
			+	"destcause_location decimal, "
		    +	"destcause_value decimal, "
		    +	"destipaddr text, "
		    +	"destlegcallidentifier int, "
		    +	"destmediacap_maxframesperpacket int, "
		    +	"destmediacap_payloadcapability int, "
		    +	"destmediatransportaddress_ip text, "
		    +	"destmediatransportaddress_port int, "
		    +	"destnodeid int, "
		    +	"destprecedencelevel decimal, "
		    +	"destspan int, "
		    +	"finalcalledpartynumber int, "
		    +	"finalcalledpartyunicodeloginuserid text, "
		    +	"globalcallid_callid int, "
		    +	"globalcallid_callmanagerid int, "
		    +	"incomingprotocolcallref text, "
		    +	"incomingprotocolid int, "
		    +	"originalcalledpartynumber int, "
		    +	"origlegcallidentifier int, "
		    +	"origrsvpaudiostat float, "
		    +	"origrsvpvideostat float, "
		    +	"origvideotransportaddress_port int, "
		    +	"outgoingprotocolcallref text, "
		    +	"outgoingprotocolid int, "
		    +	"PRIMARY KEY (datetimeorigination, num))";
		    
	public static final String SCHEMA_2_PROJ = "CREATE TABLE project.t2 ("
			+	"num bigint, "
			+	"datetimeorigination int, "
			+	"cdrrecordtype float, "
			+	"destcause_location decimal, "
		    +	"destcause_value decimal, "
		    +	"destipaddr text, "
		    +	"destlegcallidentifier int, "
		    +	"destmediacap_maxframesperpacket int, "
		    +	"destmediacap_payloadcapability int, "
		    +	"destmediatransportaddress_ip text, "
		    +	"destmediatransportaddress_port int, "
		    +	"destnodeid int, "
		    +	"destprecedencelevel decimal, "
		    +	"destspan int, "
		    +	"finalcalledpartynumber int, "
		    +	"finalcalledpartyunicodeloginuserid text, "
		    +	"globalcallid_callid int, "
		    +	"globalcallid_callmanagerid int, "
		    +	"incomingprotocolcallref text, "
		    +	"incomingprotocolid int, "
		    +	"originalcalledpartynumber int, "
		    +	"origlegcallidentifier int, "
		    +	"origrsvpaudiostat float, "
		    +	"origrsvpvideostat float, "
		    +	"origvideotransportaddress_port int, "
		    +	"outgoingprotocolcallref text, "
		    +	"outgoingprotocolid int, "
		    +	"PRIMARY KEY (datetimeorigination, num))";	    
		    
	public static final String SCHEMA_3_DEMO = "CREATE TABLE demo.t3 ("
			+	"num bigint, "
			+	"datetimeorigination timestamp, "
			+	"datetimeconnect timestamp, "
			+	"datetimedisconnect timestamp, "
			+	"destcallterminationonbehalfof int, "
		    +	"destdevicename text, "
		    +	"destrsvpaudiostat decimal, "
		    +	"destrsvpvideostat decimal, "
		    +	"destvideocap_bandwidth int, "
		    +	"destvideocap_bandwidth_channel2 int, "
		    +	"destvideocap_codec decimal, "
		    +	"destvideocap_codec_channel2 decimal, "
		    +	"destvideocap_resolution decimal, "
		    +	"destvideocap_resolution_channel2 decimal, "
		    +	"destvideochannel_role_channel2 int, "
		    +	"destvideotransportaddress_ip text, "
		    +	"destvideotransportaddress_ip_channel2 text, "
		    +	"destvideotransportaddress_port int, "
		    +	"destvideotransportaddress_port_channel2 int, "
		    +	"duration int, "
		    +	"finalcalledpartynumberpartition text, "
		    +	"lastredirectdn text, "
		    +	"lastredirectdnpartition text, "
		    +	"numberpartition text, "
		    +	"origcalledpartyredirectonbehalfof int, "
		    +	"origcallterminationonbehalfof int, "
		    +	"origdevicename text, "
		    +	"originalcalledpartynumberpartition text, "
		    +	"pkid text, "
		    +	"PRIMARY KEY (datetimeconnect, destdevicename))";
		   
		    
	public static final String SCHEMA_3_PROJ = "CREATE TABLE project.t3 ("
			+	"num bigint, "
			+	"datetimeorigination timestamp, "
			+	"datetimeconnect timestamp, "
			+	"datetimedisconnect timestamp, "
			+	"destcallterminationonbehalfof int, "
		    +	"destdevicename text, "
		    +	"destrsvpaudiostat decimal, "
		    +	"destrsvpvideostat decimal, "
		    +	"destvideocap_bandwidth int, "
		    +	"destvideocap_bandwidth_channel2 int, "
		    +	"destvideocap_codec decimal, "
		    +	"destvideocap_codec_channel2 decimal, "
		    +	"destvideocap_resolution decimal, "
		    +	"destvideocap_resolution_channel2 decimal, "
		    +	"destvideochannel_role_channel2 int, "
		    +	"destvideotransportaddress_ip text, "
		    +	"destvideotransportaddress_ip_channel2 int, "
		    +	"destvideotransportaddress_port int, "
		    +	"destvideotransportaddress_port_channel2 int, "
		    +	"duration int, "
		    +	"finalcalledpartynumberpartition text, "
		    +	"lastredirectdn text, "
		    +	"lastredirectdnpartition text, "
		    +	"numberpartition text, "
		    +	"origcalledpartyredirectonbehalfof int, "
		    +	"origcallterminationonbehalfof int, "
		    +	"origdevicename text, "
		    +	"originalcalledpartynumberpartition text, "
		    +	"pkid text, "
		    +	"PRIMARY KEY (datetimeconnect, destdevicename))";	    
}
